### ISSUE TITLE
关于移动端的后台

### ISSUE THREAD

**Issue by Fukago** [zxiaofan/YunYiAPP#1]
您好，关于登陆之后的功能显示能给个权限访问一下吗？后台一直是关着的吧，登陆的回调一直是请求态

**Comment by zxiaofan** [comment]
服务端代码也是开源的，详见https://github.com/zxiaofan/MedicalAssistanService，可直接下载源码搭建服务端系统，源码包含升库sql和数据sql（https://github.com/zxiaofan/MedicalAssistanService/tree/master/WebContent/WEB-INF/sql），可直接部署服务端。
